// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYzVMbjSomUSVKjIKaGEHtQncmc49zNNo',
    appId: '1:324791392276:web:12f0ec861783640552af01',
    messagingSenderId: '324791392276',
    projectId: 'dssdd-d7d22',
    authDomain: 'dssdd-d7d22.firebaseapp.com',
    storageBucket: 'dssdd-d7d22.appspot.com',
    measurementId: 'G-RJSKCTH755',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLpFbU54dH9r3gikOG7YF0kEsA0Y2YQ4',
    appId: '1:324791392276:android:9fa2f2844c089c5152af01',
    messagingSenderId: '324791392276',
    projectId: 'dssdd-d7d22',
    storageBucket: 'dssdd-d7d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgAPMrR6mlRf59MXnD5yI9DYqTg1Si0k0',
    appId: '1:324791392276:ios:901b6db62df7d86d52af01',
    messagingSenderId: '324791392276',
    projectId: 'dssdd-d7d22',
    storageBucket: 'dssdd-d7d22.appspot.com',
    iosClientId: '324791392276-emi2kgbsd3pu9p6fkbaot6hs19sqij6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocaMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgAPMrR6mlRf59MXnD5yI9DYqTg1Si0k0',
    appId: '1:324791392276:ios:f459f1faa336b06852af01',
    messagingSenderId: '324791392276',
    projectId: 'dssdd-d7d22',
    storageBucket: 'dssdd-d7d22.appspot.com',
    iosClientId: '324791392276-pg6lt861nd4hnkhdm4kstfa1phdjno1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocaMemo.RunnerTests',
  );
}
