// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'image_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'image_model.g.dart';

@freezed
class ImageModel with _$ImageModel {
  const factory ImageModel({
    String? id,
    String? linkUrl,
    int? price,
    int? numberSet,
  }) = _ImageModel;

  factory ImageModel.fromJson(Map<String, Object?> json)
  => _$ImageModelFromJson(json);
}